# Generated by Django 4.1 on 2022-08-25 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listings',
            name='type',
            field=models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothing'), ('PT', 'Posters'), ('ML', 'Miscellaneous')], default='RC', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
