# Generated by Django 4.1 on 2022-08-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_description_listings_sold_listings_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='Band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
