# Generated by Django 4.1 on 2022-08-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listings_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='Band',
            new_name='band',
        ),
    ]
